version: '3.7'

services:
    postgres:
        image: postgres:12.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "carrot-elephant-jackal"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    service:
        build:
            context: ./service
            dockerfile: Dockerfile
        image: mjheverett/bookmode-api:latest
        volumes:
            - /app/node_modules
            - ./service/config:/app/config
        ports:
            - "3000:3000"
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: mjheverett/bookmode-client:latest
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "8080:5000"